### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by leibaozai** [icodesign/Potatso-iOS#1]
clang: error: no such file or directory: '/Users/renpeng/Documents/Potatso-iOS/Library/ShadowPath/ShadowPath/shadowsocks-libev/libipset/set/inspection.c'
该怎么处理？

**Comment by red3** [comment]
ShadowPath target 下 缺少了 shadowsocks-libev 项目下的文件，你应该先下载 shadowsocks-libev 项目文件，地址是 https://github.com/shadowsocks/shadowsocks-libev

**Comment by icodesign** [comment]
更新一下最新版本，然后执行 git submodule update --init

**Comment by mashun** [comment]
shadowsocks-libev这个下载完，怎么弄

**Comment by yangwenmai** [comment]
@icodesign “更新一下最新版本，然后执行 git submodule update --init”
还是出现Build Failed: 'config.h' file not found。

**Comment by landryshuai** [comment]
同样出现 Build Failed: 'config.h' file not found。

**Comment by delayhsiao** [comment]
同样出现 Build Failed: 'config.h' file not found。纠结了很久也没找到怎么处理，看了一下屏蔽列表，似乎让官方给屏蔽了，求放出

**Comment by mashun** [comment]
同样出现Build Failed: 'config.h' file not found。我开发群中，之前有一个哥们上周四还可以运行起来，现在不知道怎么回事

**Comment by passol1988** [comment]
出现一样的问题 ……

**Comment by xiaobuu** [comment]
+1

**Comment by ZHSD** [comment]
文件下载下来怎么添加进去 @icodesign
