### ISSUE TITLE
想法

### ISSUE THREAD

**Issue by remaerd** [icodesign/Potatso-iOS#3]
在推上看到项目开源的新闻，快手买了一个回来用。感谢 Contribution。

几个想法：

- 最近请求部分，可直接点击来添加规则。
- 将 “更多” Tab 处的 URL 导入和二维码导入移到 “首页” 的 ＋ 按钮。
- 我一直想禁掉 Crashlytics 和 Potatso REST 服务器。我不知道你的软件会发些什么东西到你的服务器。我希望能够让我的设备更安全，尽量控制我的设备能够发送什么东西出去。

最终还是特别感谢你开发这个项目而且开源，有机会一定为项目做 Contribution.

**Comment by icodesign** [comment]
感谢反馈。

> 最近请求部分，可直接点击来添加规则

这部分还没有时间来加强，目前主要集中在代理方面。

> 将 “更多” Tab 处的 URL 导入和二维码导入移到 “首页” 的 ＋ 按钮

这个交互问题以前考虑过多次，是从首页移出去的，考虑到使用频率较低。

> 我不知道你的软件会发些什么东西到你的服务器。我希望能够让我的设备更安全，尽量控制我的设备能够发送什么东西出去

这个你可以放心。

- Crashlytics 是 Twitter 的崩溃采集服务，方便监控 App 闪退问题。
- Potatso 是开源的，传输了什么内容，都是可以在源码中看到的，我没必要去控制其它的东西。
