### ISSUE TITLE
In BaseModel.swift is wrong?

### ISSUE THREAD

**Issue by StoneLeon** [icodesign/Potatso-iOS#6]
I don't understand why show a No such module 'RealmSwift'?

**Comment by kidneyband** [comment]
same issue for me.

**Comment by itrmit** [comment]
Me too

**Comment by red3** [comment]
please `brew install carthage` and `carthage update`.

**Comment by hc2088** [comment]
啃爹货，对不起这500多个star

**Comment by IDrinkMoreWater** [comment]
碰到同样问题，pod安装realm和realmswift，引入framework和点.a，添加header search path 统统不行，小白昨晚搞了一个晚上，说出来都是泪啊

**Comment by icodesign** [comment]
@IDrinkMoreWater [Setup Guide](../wiki/Setup-Guide)
