### ISSUE TITLE
编译时 deanimate.h 文件出现Conflicting types for 'buf_free'

### ISSUE THREAD

**Issue by imphila** [icodesign/Potatso-iOS#7]
deanimate.c文件也有几处报错。都是由buf_free引起的。报错的内容是：
“Conflicting types for 'buf_free'”，
"Implicit declaration of function ‘buf_free’ is invalid in C99",
"Declaration of 'buf_free' must be import from module ‘Darwin.sys.buf before it is required’"

**Comment by clarenceli** [comment]
试着把PacketTunnel中的ShadowPath.xcodeproj去掉引用

**Comment by icodesign** [comment]
目前只能在真机上编

**Comment by tsl0922** [comment]
应该是因为模拟器的系统头文件(sys/buf.h)里已经定义了 buf_free 这个函数名，我把函数名改了下（buf_free -> buffer_free）编译成功了，但是模拟器好像测试不了 VPN 类型的应用，连接的时候报错：Fail to switch VPN.(IPC failed)，免费的开发者账号很多权限没有，所以没有付费账号应该可以放弃了，模拟器和真机都玩不了。。

免费账号会遇到的一些错误信息：
```
The 'Apple Push Notification' feature is only available to users enrolled in Apple Developer Program
Your account does not have sufficient permissions to modify containers
```

![image](https://cloud.githubusercontent.com/assets/1680515/16360417/557758f0-3b94-11e6-8bdb-4c35dc943410.png)

**Comment by tsl0922** [comment]
我在模拟器里折腾的过程中发现好像已添加的 Proxy 还不能编辑？只看到删除按钮。 @icodesign

虽然已经在用 Shadowrocket 了，还是要来支持下作者的开源行为的 👍 👍 👍

**Comment by icodesign** [comment]
@tsl0922 没有开发者帐号肯定是编不了的，除了 `Push Notification`，还需要 `Network Extension` 的证书

**Comment by tsl0922** [comment]
@icodesign 取消 Push Notification 可以编译成功并在模拟器里运行，但是用不了 Network Extension 和通知中心插件，不折腾了 😄 。
