### ISSUE TITLE
Build Failed: 'config.h' file not found

### ISSUE THREAD

**Issue by zhuscat** [icodesign/Potatso-iOS#8]
我直接下载 shadowsocks-libev 然后拖进去的，编译的时候出现这个错误。
希望能够解答，谢谢！

**Comment by zhuscat** [comment]
下载作者 Fork 的 shadowsocks-libev 就行了

**Comment by icodesign** [comment]
请参考 #5

**Comment by passol1988** [comment]
执行 git submodule update --init
还是出现Build Failed: 'config.h' file not found
不知道还有啥要注意的步骤？

**Comment by xiaobuu** [comment]
+1 还是not found
